apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: encounter
build:
  artifacts:
  - image: vincentvella/encounter-video
    context: video
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s/config-map.yaml
    - k8s/ingress-service.yaml
    - k8s/postgres-deployment.yaml
    - k8s/redis-deployment.yaml
    - k8s/video-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: video-deployment
    port: 9000
  - resourceType: deployment
    resourceName: postgres-deployment
    port: 5432