apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    component: video
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: video
  template:
    metadata:
      labels:
        component: video
    spec:
      containers:
        - name: video
          image: vincentvella/encounter-video
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: PG_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PG_HOST
              value: postgres-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres